 ## Get used With Tensorflow fondamentals :
 * Introduction to Tensors.
 * Getting information from Tensors.
 * Manipulating Tensors.
 * Tensors & Numpy.
 * Using @tf.function (to speed up regular Python functions).
 * Using GPUs with TensorFlow (Or TPUs).
 * Exercices.

## Introduction to Tensors 



In [1]:
# Import TensorFlow & Check Version :
import tensorflow as tf;
print(tf.__version__);


2.12.0


In [2]:
# Create Tensors with tf.constant() // This function is not commonly used; most developers use tf.io and tf.data, which can read data from various sources
scalar =tf.constant(7);
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimension of an Tensor (ndim)
scalar.ndim # maybe ==0 because shape containt Zero element 'shape=()'... We'll see ;)

0

In [4]:
# Create a Vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of the vector
vector.ndim # maybe ==1 because shape contains one elements 'shape=(2,)'... We'll see ;) 

1

In [6]:
# Create a Matrix
matrix=tf.constant([[1,2],[2,1]])
matrix # The Shape is (Number-Rows,Number-Columns)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 1]], dtype=int32)>

In [7]:
# Check the dimension of the matrix
matrix.ndim # maybe ==2 because shape contains two elements 'shape=(2, 2)'... We'll see ;)

2

In [8]:
# Create another Matrix with float16 as dtype instead of int32
matrix2=tf.constant([[1,2,3] , [4,5,6] , [7, 8 ,9]] ,dtype=tf.float16) #custumizing dtype can be usefull when you have an error related to the import of a specefic type of data.
matrix2

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float16)>

In [9]:
# Check the dimension of the matrix2
matrix.ndim # maybe ==2 because shape contains two elements 'shape=(3, 3)'... We'll see ;)

2

In [10]:
# Create a tensor
tensor = tf.constant([
                     [[1,2,3],[4,5,6],[7, 8 ,9]], #1st Matrix
                     [[1,2,3] , [4,5,6] , [7, 8 ,9]], #2st Matrix
                     [[1,2,3] , [4,5,6] , [7, 8 ,9]] #3st Matrix
                      ])
tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [11]:
# Check the dimension of the tensor *
tensor.ndim  # maybe ==3 because tensor.shape contains three elements 'shape=(3, 3, 3)'... We'll see ;)

3

# Resume :
* Scalar : Single number.
* Vector : A number with a direction (e.g wind /speed /direction).
* Matrix : 2 dimensional array of number.
* Tensor : n*dimensional array of numbers.


=> The dimension is the number of the shape elements.


In [12]:
# tf.variable vs tf.constant
constTensor =tf.constant([10,7]);
varTensor = tf.Variable([10,7]);
constTensor,varTensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# assign values to varTensor with assign()
varTensor[0].assign(7);
varTensor
# That's not possible with constTensor because it contains constants.

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [14]:
# Create tensor throw ts.random() .
# Useful when we need to initialize tensors for initial weights.
randTensor=tf.random.uniform(shape=[3,5,3],minval=10, maxval=100, dtype=tf.int64);
randTensor

<tf.Tensor: shape=(3, 5, 3), dtype=int64, numpy=
array([[[93, 43, 12],
        [48, 96, 26],
        [48, 30, 13],
        [51, 91, 59],
        [80, 28, 61]],

       [[43, 57, 23],
        [85, 15, 41],
        [96, 60, 25],
        [95, 74, 23],
        [69, 68, 33]],

       [[78, 88, 17],
        [78, 86, 66],
        [82, 33, 89],
        [69, 37, 59],
        [39, 14, 63]]])>

In [15]:
random_1=tf.random.Generator.from_seed(40); 
random_1=random_1.normal(shape=[3,2]);
random_2=tf.random.Generator.from_seed(40); 
random_2=random_2.normal(shape=[3,2]);
random_1, random_2, random_1== random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.78953624,  0.53897345],
        [-0.48535708,  0.74055266],
        [ 0.31662667, -1.4391748 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.78953624,  0.53897345],
        [-0.48535708,  0.74055266],
        [ 0.31662667, -1.4391748 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [16]:
# Shuffle the order of elements, which is useful when you need to avoid organized input data (for example, 10000 spaghetti / 10000 ramen). This order can affect model learning, which is why it's beneficial to shuffle them.
not_shuffled=tf.constant([[1,2],
                         [3,4],
                         [5,6]]);
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [17]:
tf.random.shuffle.seed=40; # global seed
not_shuffled=tf.random.shuffle(not_shuffled, seed=40); # Operational seed.
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2],
       [5, 6]], dtype=int32)>

In [18]:
# Other ways to create Tensors.
tf.ones([10,7]) # Create a tensor of all ones.

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [19]:
tf.zeros([10,7]) # Create a tensor of all zeros.

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [20]:
# Turn Numpy arrays to tensors.
# The main difference between Numpy arrays and Tensorflow tensors is that tensors can be run on GPUs.
import numpy as np;
np_array=np.arange(1,25,dtype=np.int32); # Create array with 1 to 25 element
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [21]:
# Cast numpy array to tensor:
A=tf.constant(np_array) 
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [22]:
# Cast numpy array to tensor with shape =[2,3,4]:
A2=tf.constant(np_array, shape=[2,3,4]) ;
A2

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting informations from tensors like (Size, Shape(ndim), Dimensions, Axis).

In [23]:
# Create a rank 4 tensor:
rank4_tensor=tf.zeros([2,3,4,5]);
rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
rank4_tensor[0]
rank4_tensor.shape , rank4_tensor.ndim ,tf.size(rank4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [25]:
# Get various attributes of our tensor:
print("Data Type of each element is:",rank4_tensor.dtype)
print("Number of dimention is:",rank4_tensor.ndim);
print("The shape of our tensor is:",rank4_tensor.shape);
print("Elements along 0 axis:",rank4_tensor.shape[-1]);
print("Elements along last axis:",rank4_tensor.shape[-1]);
print("Total lements our tensor:",tf.size (rank4_tensor));
print("Total lements our tensor:",tf.size (rank4_tensor).numpy());


Data Type of each element is: <dtype: 'float32'>
Number of dimention is: 4
The shape of our tensor is: (2, 3, 4, 5)
Elements along 0 axis: 5
Elements along last axis: 5
Total lements our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total lements our tensor: 120


### Indexing Tensors:
Tensors can be indexed just like python list.

In [26]:
some_list=[1,2,3,4,5];
some_list[:2]

[1, 2]

In [27]:
rank4_tensor[:2,:2,:2,:2] # Get the first two elements from each dimension.

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [28]:
 # Get the first two element from each dimension except the last dimension. 
 rank4_tensor[:1,:1,:1] 

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [29]:
 # Get one dimension  elements. 
rank4_tensor[:,:1,:1,:1] 
rank4_tensor[:1,:,:1,:1] 
rank4_tensor[:1,:1,:,:1] 
rank4_tensor[:1,:1,:1,:] 

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

reshape : Changing or adding an extra dimension


In [30]:
# create 2 dimensional tensor
rank2_tensor=tf.constant([[1,2],[3,4]])
rank2_tensor;
rank2_tensor.shape, rank2_tensor.ndim

(TensorShape([2, 2]), 2)

In [31]:
#Get last item of each dimension:
rank2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [32]:
# add extra dimension : M1(tf.newaxis)
rank3_tensor=rank2_tensor[...,tf.newaxis] # ... means every axis that already exists.
rank3_tensor


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [33]:
# add extra dimension : M1(tf.expand_dims)
tf.expand_dims(rank2_tensor, axis=-1) # -1 : expand the final axis.

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [34]:
tf.expand_dims(rank2_tensor,axis=0) # 0  expand the first axis. 

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

### Manipulating Tensors (tensors operations)
If data is stored in tensors, finding patterns within these tensors often involves manipulating tensors. When building models with TensorFlow, much of the pattern discovery within tensors is done for you; however, oftentimes that pattern discovery is through the extended use of a few basic operations !

Addition operator:

In [35]:
tensor=tf.constant([[10,7],
                    [3,4]])
tensor+10
tf.add(tensor,10) # With Tensorflow built-in function (executed with GPU !)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

Multiplication operator(with value):


In [36]:
tensor*10
tf.multiply(tensor,10) # With Tensorflow built-in function (executed with GPU !)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

Substriction operator:

In [37]:
tensor-1
tf.subtract(tensor,1) # With Tensorflow built-in function (executed with GPU !)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 6],
       [2, 3]], dtype=int32)>

Divisional operator:


In [38]:
tensor/10
tf.divide(tensor,10) # With Tensorflow built-in function (executed with GPU !)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

Matrix multiplication (Also known as dot product)


In [39]:
M1=tf.constant([[1,2,3],
    [4,5,6]]);
M2=tf.constant([[5,6],
 [7,8],
 [9,10]])
multiplication_result=tf.matmul(M1,M2); # multiplication using Tensorflow (GPU)
multiplication_result

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 46,  52],
       [109, 124]], dtype=int32)>

In [40]:
# Multiplication using python  operator "@"
M1 @ M2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 46,  52],
       [109, 124]], dtype=int32)>

In [41]:
#Reshape a matrix (useful when you have to multiply two tensors, but the inner dimension doesn't match).
M3=tf.constant([[1,2,3],
              [4,5,6],
               [7,8,9]])
M3.shape

TensorShape([3, 3])

In [42]:
tf.reshape(M3,[9,])

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [43]:
# Transpose a matrix 
M3 ,tf.transpose(M3)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]], dtype=int32)>)

In [44]:
# This kind of data manipulation can be really useful in ML and DL, reshaping the data into tensors and preparing them for use.

In [45]:
# Doing some data manipulations :
# Initialize  M1 :
M1= tf.constant([[1,2,3,4],[5,6,7,8],[9,10,11,12]]); 
M1

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int32)>

In [46]:
# Initialize M2 
M2=tf.constant([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])
M2

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [47]:
# Can't do M1*M2 because Inner dimensions of the two matrix dosen't fit:
# So we have to reshape either M1 or M2
# Lets reshape M2
M2_reshaped=tf.reshape(M2,(4,6))


In [48]:
# Matrix multiplication between M1 and M2_reshaped
tf.matmul(M1,M2_reshaped)

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[130, 140, 150, 160, 170, 180],
       [290, 316, 342, 368, 394, 420],
       [450, 492, 534, 576, 618, 660]], dtype=int32)>

In [49]:
# Generarly when performing matrix multiplication on two tensors and one of the axes dosen't line up, you will transpose (rather than reshape)one of the tensors in order to satisfy the matrix multiplications rules

Changing the datatype of a tensor

In [50]:
# create a new tensor with default datatype(float32)
floatTensor=tf.constant([[1.7,1.2],[1.1,1.3]])
floatTensor.dtype

tf.float32

In [51]:
# Change data from float32 to float16(reduced precision)
tf.cast(floatTensor,dtype=tf.float16)


<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1.7, 1.2],
       [1.1, 1.3]], dtype=float16)>

In [52]:
tf.cast(tf.cast(floatTensor,dtype=tf.int16),dtype=tf.float32)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

### Aggregating tensors (condensing them from multiple values down to a smaller amount of val) :



In [53]:
# Get the absolute values
simple_tensor=tf.constant([[-10,-7],[7,10]])
tf.abs(simple_tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

Let's go through the rollowing forms of aggregation:

	*Get the minimum
	*Get the maximum
	*Get the mean of a tensor
	*Get the sum of a tensor


In [54]:
# Create random tensor:
simple_random_tensor=tf.constant(np.random.randint(-100,100,900))
simple_random_tensor.shape,simple_random_tensor.ndim, tf.size(simple_random_tensor)
tf.reshape(simple_random_tensor, shape=(6,6,25))

<tf.Tensor: shape=(6, 6, 25), dtype=int64, numpy=
array([[[  97,  -20,   24,   32,   81,  -37,   88,  -68,  -75,  -18,
          -60,   83,  -90,  -54,  -66,   22,   11,  -39,  -52,  -87,
          -36,    2,   54,  -60,  -46],
        [ -70,   95,    4,   35,   30,   68,  -34,  -18,   74,  -82,
          -12,  -77,  -39,  -68,   -7,  -53,    2,   32,  -77,   86,
          -24,   78,    5,    9,  -39],
        [  13,   74,   60,   67,   74,  -69,  -34,    7,   65,  -57,
           68,   44,  -88,   21,  -63,   17,    7,   56,   61,   36,
          -86,  -95,   69,  -30,  -19],
        [ -66,   -8,   34,   93,  -22,  -12,   41,   64,  -32,   -4,
           94,   62,  -88,  -45,  -10,   35,   98,   -3,  -17,    1,
           92,  -32,   59,  -93,   -5],
        [ -79,   77,  -76,   39,  -73,   56,  -72,   34,  -71,   46,
          -27,  -96,  -37,   12,  -43,   83,   92,  -29,  -34,   92,
          -12,  -19,  -90,   47,   24],
        [  58,  -53,   -8,   27,    6,   50,   79,  -51,   3

In [55]:
# minimum
simple_tensor_min=tf.reduce_min(simple_random_tensor)
simple_tensor_min

<tf.Tensor: shape=(), dtype=int64, numpy=-100>

In [56]:
# maximum
simple_tensor_max=tf.reduce_max(simple_random_tensor)
simple_tensor_max

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [57]:
# mean 
simple_tensor_mean =tf.reduce_mean(simple_random_tensor)
simple_tensor_mean 

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [58]:
# sum  
simple_tensor_sum  =tf.reduce_sum(simple_random_tensor)
simple_tensor_sum 

<tf.Tensor: shape=(), dtype=int64, numpy=1000>

In [59]:
# variance
simple_random_tensor=tf.cast(simple_random_tensor,dtype=tf.float32) # convert the tensor to a floating-point type explicitly before calculating the variance to avoid numerical instability during the conversion and subsequent variance calculation.
tf.math.reduce_variance(simple_random_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=3379.5767>

In [60]:
# standard deviation
tf.math.reduce_std(simple_random_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=58.134125>

:# Find the positional maximum and minimum

In [61]:
# Create a new tensor for finding positional minimum and maxmimum
tf.random.set_seed(42)
simple_random_tensor=tf.random.uniform(shape=(50,))
simple_random_tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [62]:
# Find the positional maximum
tf.argmax(simple_random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [63]:
# Print the maximum
simple_random_tensor[tf.argmax(simple_random_tensor)]


<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [64]:
# check equality between reduce_max & simple_random_tensor[tf.argmax(simple_random_tensor)]=
tf.assert_equal(tf.reduce_max(simple_random_tensor),simple_random_tensor[tf.argmax(simple_random_tensor)])

In [65]:
# find positional minimum
tf.argmin(simple_random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [66]:
# Print the minimum
simple_random_tensor[tf.argmin(simple_random_tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [67]:
# check equality between reduce_min & simple_random_tensor[tf.argmin(simple_random_tensor)]=
tf.assert_equal(tf.reduce_min(simple_random_tensor),simple_random_tensor[tf.argmin(simple_random_tensor)])

Squeezing a tensor(removing all single dimensions)

In [68]:
simple_random_tensor=tf.reshape(simple_random_tensor,shape=[1,1,1,50])
simple_random_tensor

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [69]:
tf.squeeze(simple_random_tensor)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### One-hot encoding tensors
In order to transmit the data to our neural network, we need to encode it using numerical encoding. One-hot encoding, being a type of numerical encoding, serves as an effective method for this purpose.

In [73]:
# Create a list of indices
my_list = [1, 2, 3, 4, 5]
numpy_array = np.array(my_list)
numpy_array

array([1, 2, 3, 4, 5])

In [86]:
# One hot encode our list of indices
tf.one_hot(numpy_array, depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [90]:
# One hot encode our list using offValue and onValue
tf.one_hot(numpy_array, depth=5,on_value=1, off_value=-1 )

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[-1,  1, -1, -1, -1],
       [-1, -1,  1, -1, -1],
       [-1, -1, -1,  1, -1],
       [-1, -1, -1, -1,  1],
       [-1, -1, -1, -1, -1]], dtype=int32)>

Squaring, log, square root

In [101]:
# Create a new tensor  
simple_vector=tf.range(1,10)
simple_vector

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [97]:
# Square it
tf.math.square(simple_vector)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [106]:
# Find the squareroot (Will error, method requxres non—xnt type )
simple_vector=tf.cast(simple_vector,dtype=tf.float16)
tf.sqrt(simple_vector)

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [108]:
# Find the log
tf.math.log(simple_vector)

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

In [110]:
# Find the log_sigmoid
tf.math.log_sigmoid(simple_vector)

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([-3.132e-01, -1.270e-01, -4.858e-02, -1.814e-02, -6.714e-03,
       -2.476e-03, -9.112e-04, -3.355e-04, -1.234e-04], dtype=float16)>

In [112]:
# Find the log_softmax
tf.math.log_softmax(simple_vector)

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([-8.46  , -7.457 , -6.457 , -5.457 , -4.457 , -3.459 , -2.459 ,
       -1.459 , -0.4587], dtype=float16)>

In [114]:
# Find the sin(x)
tf.math.sin(simple_vector)

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([ 0.8413,  0.909 ,  0.1411, -0.757 , -0.959 , -0.2793,  0.657 ,
        0.9893,  0.412 ], dtype=float16)>

In [116]:
# Find the tan(x)
tf.math.tan(simple_vector)

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([ 1.558 , -2.186 , -0.1426,  1.158 , -3.38  , -0.291 ,  0.8716,
       -6.8   , -0.4524], dtype=float16)>

### Tensors and NumPpy (The fundamental package for scientific computing with Python): 

In [123]:
# Create a tensor directly from a NumPy array
np_simple_array=np.array([10,11,12,13,14,15],dtype=np.float16)
tf.constant(np_simple_array)

<tf.Tensor: shape=(6,), dtype=float16, numpy=array([10., 11., 12., 13., 14., 15.], dtype=float16)>

In [129]:
# Convert our tensor back to a NumPy array
np.array(np_simple_array), type(np.array(np_simple_array))

(array([10., 11., 12., 13., 14., 15.], dtype=float16), numpy.ndarray)

In [130]:
np.array(np_simple_array)[0]

10.0

In [134]:
# The default types of each are slightly different
A=tf.constant(np.array([1.,2.,3.,4.,5.]))
B=tf.constant([1.,2.,3.,4.,5.])
# Check the datatypes of each
A.dtype,B.dtype

(tf.float64, tf.float32)

In [138]:
#Create an array with evenly spaced values within a specified range.
np.arange(1,20,2)


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [140]:
#Create an array with a specified number of evenly spaced values within a specified range.
# Create an array with 5 values from 0 to 1 (inclusive)
arr = np.linspace(0, 1, num=5)
print(arr)
# Output: [0.   0.25 0.5  0.75 1.  ]

# Create an array with 10 values from 1 to 2 (exclusive)
arr2 = np.linspace(1, 2, num=10, endpoint=False)
print(arr2)

[0.   0.25 0.5  0.75 1.  ]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


In [143]:
# Create an array filled with zeros / np.zeros(shape, dtype=float, order='C')
arr2 = np.zeros((3, 2))
print(arr2)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [146]:
# Create an array filled with ones.
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [153]:
# Create a 2-D identity matrix or a diagonal array with ones on the diagonal and zeros elsewhere.
# Also known as a unit matrix. An identity matrix is a square matrix with ones on the main diagonal and zeros elsewhere.
# Create a 4x5 identity matrix with an offset diagonal
arr2 = np.eye(4, 5, k=1)
arr2

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Return elements from two arrays based on a condition.

In [157]:
# Use np.where() to find indices where elements are greater than 2
indices = np.where(arr > 0)
print(indices)

(array([1, 2, 3, 4]),)


In [158]:
# Use np.where() with x and y arguments
result = np.where(arr > 0, "Greater", "Less or equal")
print(result)

['Less or equal' 'Greater' 'Greater' 'Greater' 'Greater']
