 ## Get used With Tensorflow fondamentals :
 * Introduction to Tensors.
 * Getting information from Tensors.
 * Manipulating Tensors.
 * Tensors & Numpy.
 * Using @tf.function (to speed up regular Python functions).
 * Using GPUs with TensorFlow (Or TPUs).
 * Exercices.

 ## Introduction to Tensors 



In [ ]:
# Import TensorFlow & Check Version :
import tensorflow as tf;
print(tf.__version__);


2.12.0


In [ ]:
# Create Tensors with tf.constant() // This function is not commonly used; most developers use tf.io and tf.data, which can read data from various sources
scalar =tf.constant(7);
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimension of an Tensor (ndim)
scalar.ndim # maybe ==0 because shape containt Zero element 'shape=()'... We'll see ;)

0

In [ ]:
# Create a Vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of the vector
vector.ndim # maybe ==1 because shape contains one elements 'shape=(2,)'... We'll see ;) 

In [ ]:
# Create a Matrix
matrix=tf.constant([[1,2],[2,1]])
matrix # The Shape is (Number-Rows,Number-Columns)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 1]], dtype=int32)>

In [ ]:
# Check the dimension of the matrix
matrix.ndim # maybe ==2 because shape contains two elements 'shape=(2, 2)'... We'll see ;)

2

In [ ]:
# Create another Matrix with float16 as dtype instead of int32
matrix2=tf.constant([[1,2,3] , [4,5,6] , [7, 8 ,9]] ,dtype=tf.float16) #custumizing dtype can be usefull when you have an error related to the import of a specefic type of data.
matrix2

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float16)>

In [ ]:
# Check the dimension of the matrix2
matrix.ndim # maybe ==2 because shape contains two elements 'shape=(3, 3)'... We'll see ;)

2

In [35]:
# Create a tensor
tensor = tf.constant([
                     [[1,2,3],[4,5,6],[7, 8 ,9]], #1st Matrix
                     [[1,2,3] , [4,5,6] , [7, 8 ,9]], #2st Matrix
                     [[1,2,3] , [4,5,6] , [7, 8 ,9]] #3st Matrix
                      ])
tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [36]:
# Check the dimension of the tensor *
tensor.ndim  # maybe ==3 because tensor.shape contains three elements 'shape=(3, 3, 3)'... We'll see ;)

3

# Resume :
* Scalar : Single number.
* Vector : A number with a direction (e.g wind /speed /direction).
* Matrix : 2 dimensional array of number.
* Tensor : n*dimensional array of numbers.


=> The dimension is the number of the shape elements.
