 ## Get used With Tensorflow fondamentals :
 * Introduction to Tensors.
 * Getting information from Tensors.
 * Manipulating Tensors.
 * Tensors & Numpy.
 * Using @tf.function (to speed up regular Python functions).
 * Using GPUs with TensorFlow (Or TPUs).
 * Exercices.

 ## Introduction to Tensors 



In [49]:
# Import TensorFlow & Check Version :
import tensorflow as tf;
print(tf.__version__);


2.12.0


In [ ]:
# Create Tensors with tf.constant() // This function is not commonly used; most developers use tf.io and tf.data, which can read data from various sources
scalar =tf.constant(7);
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimension of an Tensor (ndim)
scalar.ndim # maybe ==0 because shape containt Zero element 'shape=()'... We'll see ;)

0

In [ ]:
# Create a Vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of the vector
vector.ndim # maybe ==1 because shape contains one elements 'shape=(2,)'... We'll see ;) 

1

In [ ]:
# Create a Matrix
matrix=tf.constant([[1,2],[2,1]])
matrix # The Shape is (Number-Rows,Number-Columns)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 1]], dtype=int32)>

In [ ]:
# Check the dimension of the matrix
matrix.ndim # maybe ==2 because shape contains two elements 'shape=(2, 2)'... We'll see ;)

2

In [ ]:
# Create another Matrix with float16 as dtype instead of int32
matrix2=tf.constant([[1,2,3] , [4,5,6] , [7, 8 ,9]] ,dtype=tf.float16) #custumizing dtype can be usefull when you have an error related to the import of a specefic type of data.
matrix2

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float16)>

In [ ]:
# Check the dimension of the matrix2
matrix.ndim # maybe ==2 because shape contains two elements 'shape=(3, 3)'... We'll see ;)

2

In [ ]:
# Create a tensor
tensor = tf.constant([
                     [[1,2,3],[4,5,6],[7, 8 ,9]], #1st Matrix
                     [[1,2,3] , [4,5,6] , [7, 8 ,9]], #2st Matrix
                     [[1,2,3] , [4,5,6] , [7, 8 ,9]] #3st Matrix
                      ])
tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [ ]:
# Check the dimension of the tensor *
tensor.ndim  # maybe ==3 because tensor.shape contains three elements 'shape=(3, 3, 3)'... We'll see ;)

3

# Resume :
* Scalar : Single number.
* Vector : A number with a direction (e.g wind /speed /direction).
* Matrix : 2 dimensional array of number.
* Tensor : n*dimensional array of numbers.


=> The dimension is the number of the shape elements.


In [ ]:
# tf.variable vs tf.constant
constTensor =tf.constant([10,7]);
varTensor = tf.Variable([10,7]);
constTensor,varTensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# assign values to varTensor with assign()
varTensor[0].assign(7);
varTensor
# That's not possible with constTensor because it contains constants.

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Create tensor throw ts.random() .
# Useful when we need to initialize tensors for initial weights.
randTensor=tf.random.uniform(shape=[3,5,3],minval=10, maxval=100, dtype=tf.int64);
randTensor

In [43]:
random_1=tf.random.Generator.from_seed(40); 
random_1=random_1.normal(shape=[3,2]);
random_2=tf.random.Generator.from_seed(40); 
random_2=random_2.normal(shape=[3,2]);
random_1, random_2, random_1== random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.78953624,  0.53897345],
        [-0.48535708,  0.74055266],
        [ 0.31662667, -1.4391748 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.78953624,  0.53897345],
        [-0.48535708,  0.74055266],
        [ 0.31662667, -1.4391748 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [56]:
# Shuffle the order of elements, which is useful when you need to avoid organized input data (for example, 10000 spaghetti / 10000 ramen). This order can affect model learning, which is why it's beneficial to shuffle them.
not_shuffled=tf.constant([[1,2],
                         [3,4],
                         [5,6]]);
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [63]:
tf.random.shuffle.seed=40; # global seed
not_shuffled=tf.random.shuffle(not_shuffled, seed=40); # Operational seed.
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6],
       [3, 4]], dtype=int32)>

In [ ]:
# Other ways to create Tensors.
tf.ones([10,7]) # Create a tensor of all ones.

In [ ]:
tf.zeros([10,7]) # Create a tensor of all zeros.

In [71]:
# Turn Numpy arrays to tensors.
# The main difference between Numpy arrays and Tensorflow tensors is that tensors can be run on GPUs.
import numpy as np;
np_array=np.arange(1,25,dtype=np.int32); # Create array with 1 to 25 element
np_array

In [72]:
# Cast numpy array to tensor:
A=tf.constant(np_array) 
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [73]:
# Cast numpy array to tensor with shape =[2,3,4]:
A2=tf.constant(np_array, shape=[2,3,4]) ;
A2


<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>