 ## Get used With Tensorflow fondamentals :
 * Introduction to Tensors.
 * Getting information from Tensors.
 * Manipulating Tensors.
 * Tensors & Numpy.
 * Using @tf.function (to speed up regular Python functions).
 * Using GPUs with TensorFlow (Or TPUs).
 * Exercices.

## Introduction to Tensors 



In [2]:
# Import TensorFlow & Check Version :
import tensorflow as tf;
print(tf.__version__);


2.12.0


In [3]:
# Create Tensors with tf.constant() // This function is not commonly used; most developers use tf.io and tf.data, which can read data from various sources
scalar =tf.constant(7);
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimension of an Tensor (ndim)
scalar.ndim # maybe ==0 because shape containt Zero element 'shape=()'... We'll see ;)

0

In [5]:
# Create a Vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check the dimension of the vector
vector.ndim # maybe ==1 because shape contains one elements 'shape=(2,)'... We'll see ;) 

1

In [7]:
# Create a Matrix
matrix=tf.constant([[1,2],[2,1]])
matrix # The Shape is (Number-Rows,Number-Columns)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 1]], dtype=int32)>

In [8]:
# Check the dimension of the matrix
matrix.ndim # maybe ==2 because shape contains two elements 'shape=(2, 2)'... We'll see ;)

2

In [9]:
# Create another Matrix with float16 as dtype instead of int32
matrix2=tf.constant([[1,2,3] , [4,5,6] , [7, 8 ,9]] ,dtype=tf.float16) #custumizing dtype can be usefull when you have an error related to the import of a specefic type of data.
matrix2

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float16)>

In [10]:
# Check the dimension of the matrix2
matrix.ndim # maybe ==2 because shape contains two elements 'shape=(3, 3)'... We'll see ;)

2

In [11]:
# Create a tensor
tensor = tf.constant([
                     [[1,2,3],[4,5,6],[7, 8 ,9]], #1st Matrix
                     [[1,2,3] , [4,5,6] , [7, 8 ,9]], #2st Matrix
                     [[1,2,3] , [4,5,6] , [7, 8 ,9]] #3st Matrix
                      ])
tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [12]:
# Check the dimension of the tensor *
tensor.ndim  # maybe ==3 because tensor.shape contains three elements 'shape=(3, 3, 3)'... We'll see ;)

3

# Resume :
* Scalar : Single number.
* Vector : A number with a direction (e.g wind /speed /direction).
* Matrix : 2 dimensional array of number.
* Tensor : n*dimensional array of numbers.


=> The dimension is the number of the shape elements.


In [13]:
# tf.variable vs tf.constant
constTensor =tf.constant([10,7]);
varTensor = tf.Variable([10,7]);
constTensor,varTensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# assign values to varTensor with assign()
varTensor[0].assign(7);
varTensor
# That's not possible with constTensor because it contains constants.

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
# Create tensor throw ts.random() .
# Useful when we need to initialize tensors for initial weights.
randTensor=tf.random.uniform(shape=[3,5,3],minval=10, maxval=100, dtype=tf.int64);
randTensor

<tf.Tensor: shape=(3, 5, 3), dtype=int64, numpy=
array([[[53, 45, 34],
        [94, 74, 30],
        [12, 66, 55],
        [49, 22, 62],
        [94, 39, 86]],

       [[48, 28, 77],
        [60, 32, 29],
        [63, 23, 66],
        [58, 71, 38],
        [22, 85, 74]],

       [[50, 33, 18],
        [29, 59, 31],
        [62, 98, 86],
        [51, 11, 52],
        [52, 31, 82]]])>

In [16]:
random_1=tf.random.Generator.from_seed(40); 
random_1=random_1.normal(shape=[3,2]);
random_2=tf.random.Generator.from_seed(40); 
random_2=random_2.normal(shape=[3,2]);
random_1, random_2, random_1== random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.78953624,  0.53897345],
        [-0.48535708,  0.74055266],
        [ 0.31662667, -1.4391748 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.78953624,  0.53897345],
        [-0.48535708,  0.74055266],
        [ 0.31662667, -1.4391748 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [17]:
# Shuffle the order of elements, which is useful when you need to avoid organized input data (for example, 10000 spaghetti / 10000 ramen). This order can affect model learning, which is why it's beneficial to shuffle them.
not_shuffled=tf.constant([[1,2],
                         [3,4],
                         [5,6]]);
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [18]:
tf.random.shuffle.seed=40; # global seed
not_shuffled=tf.random.shuffle(not_shuffled, seed=40); # Operational seed.
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2],
       [5, 6]], dtype=int32)>

In [19]:
# Other ways to create Tensors.
tf.ones([10,7]) # Create a tensor of all ones.

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [20]:
tf.zeros([10,7]) # Create a tensor of all zeros.

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [21]:
# Turn Numpy arrays to tensors.
# The main difference between Numpy arrays and Tensorflow tensors is that tensors can be run on GPUs.
import numpy as np;
np_array=np.arange(1,25,dtype=np.int32); # Create array with 1 to 25 element
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
# Cast numpy array to tensor:
A=tf.constant(np_array) 
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [23]:
# Cast numpy array to tensor with shape =[2,3,4]:
A2=tf.constant(np_array, shape=[2,3,4]) ;
A2

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting informations from tensors like (Size, Shape(ndim), Dimensions, Axis).

In [24]:
# Create a rank 4 tensor:
rank4_tensor=tf.zeros([2,3,4,5]);
rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
rank4_tensor[0]
rank4_tensor.shape , rank4_tensor.ndim ,tf.size(rank4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [26]:
# Get various attributes of our tensor:
print("Data Type of each element is:",rank4_tensor.dtype)
print("Number of dimention is:",rank4_tensor.ndim);
print("The shape of our tensor is:",rank4_tensor.shape);
print("Elements along 0 axis:",rank4_tensor.shape[-1]);
print("Elements along last axis:",rank4_tensor.shape[-1]);
print("Total lements our tensor:",tf.size (rank4_tensor));
print("Total lements our tensor:",tf.size (rank4_tensor).numpy());


Data Type of each element is: <dtype: 'float32'>
Number of dimention is: 4
The shape of our tensor is: (2, 3, 4, 5)
Elements along 0 axis: 5
Elements along last axis: 5
Total lements our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total lements our tensor: 120


### Indexing Tensors:
Tensors can be indexed just like python list.

In [27]:
some_list=[1,2,3,4,5];
some_list[:2]

[1, 2]

In [32]:
rank4_tensor[:2,:2,:2,:2] # Get the first two elements from each dimension.

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [33]:
 # Get the first two element from each dimension except the last dimension. 
 rank4_tensor[:1,:1,:1] 

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [36]:
 # Get one dimension  elements. 
rank4_tensor[:,:1,:1,:1] 
rank4_tensor[:1,:,:1,:1] 
rank4_tensor[:1,:1,:,:1] 
rank4_tensor[:1,:1,:1,:] 

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

reshape : Changing or adding an extra dimension


In [42]:
# create 2 dimensional tensor
rank2_tensor=tf.constant([[1,2],[3,4]])
rank2_tensor;
rank2_tensor.shape, rank2_tensor.ndim

(TensorShape([2, 2]), 2)

In [54]:
#Get last item of each dimension:
rank2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [60]:
# add extra dimension : M1(tf.newaxis)
rank3_tensor=rank2_tensor[...,tf.newaxis] # ... means every axis that already exists.
rank3_tensor


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [62]:
# add extra dimension : M1(tf.expand_dims)
tf.expand_dims(rank2_tensor, axis=-1) # -1 : expand the final axis.

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [63]:
tf.expand_dims(rank2_tensor,axis=0) # 0  expand the first axis. 

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>